services:
  - type: web
    name: minio-on-render
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /minio/health/live
    autoDeploy: false
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 1
    ports:
      - 9000
      - 9001
