services:
  - type: web
    name: minio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 1
    ports:
      - port: 80
        targetPort: 9000
